### ISSUE TITLE
New Code Not loading VCF File

### ISSUE THREAD

**Issue by mgiresi** [emmanuelparadis/New-code-for-VCF#1]
Hi,

I think that peas was updated to include the new vcc info into the workflow, but I tried to load a vcf file into R and got the following error messages (after I force quit after an hour waiting for file to load); including both command and error: 

> read.vcf("2015_termiteRF.vcf", from = 1, to = 10000, which.loci = NULL, quiet = FALSE)

Warning messages:
1: In i + 0:5 : NAs produced by integer overflow
2: In i + 0:5 : NAs produced by integer overflow
3: In i + 0:5 : NAs produced by integer overflow
4: In i + 0:5 : NAs produced by integer overflow
5: In i + 0:5 : NAs produced by integer overflow
6: In i + 1L : NAs produced by integer overflow

Also, if I try using the command to get info from the vcc file, I get the following error:

RF_info <-VCFlociinfo("2015_termiteRF.vcf")
Error: could not find function "VCFlociinfo"

**Comment by emmanuelparadis** [comment]
Hi,

It's difficult to help with the first command. Maybe your VCF file is not arranged following the standard.

For the 2nd command: the function has been renamed VCFloci(). Try with that, and you'll if you have something that makes sense.
